### ISSUE TITLE
Replace shell scripts with unit tests

### ISSUE THREAD

**Issue by sverhoeven** [xenon-middleware/xenon-tutorial#82]
At the moment a shell script can be run to test all the examples. It would be more Java like to use unit tests.

To test against slurm we could use Docker containers with www.testcontainers.org 
The same is done in the xenon-cli tests.

**Comment by jspaaks** [comment]
I think our reasoning for what to include should originate from what a newcomer needs when getting started with Xenon. From that perspective, running shell scripts like you set it up [here](https://github.com/xenon-middleware/Xenon-examples/blame/master/README.md#L16) may be preferred (I'm kind of undecided on this).

As a general remark, I think we should avoid redoing https://github.com/xenon-middleware/xenon 's ``/src/integrationTest`` directory

**Comment by jmaassen** [comment]
I think the examples should look like stand alone applications that a user can copy-paste to get started.

Doing them as unit test would make this harder for the user?

**Comment by jspaaks** [comment]
OK noted. but there are a few aspects that come into it, e.g.

- command line based v eclipse|IDEA based
- xenon-cli or ./gradlew run -Dclassname
- vm or people's own installations
- linux | windows | mac
- docker or (no docker and use real systems)
- solely Java or Java | Bash | Python like we had (but didn't use) before. How to make sure that the code examples work and keep working?

whatever we end up with is going to be a compromise no matter what.

**Comment by sverhoeven** [comment]
Yep, we want to accomplish at the same time:
1. a newcomer can run the example in the simplest least surprising way
2. the examples work by testing them on Travis

**Comment by jspaaks** [comment]
Simplest testing added using JUnit. Currently tests if no Exceptions are thrown and that's it.

Not sure how to proceed with testcontainers, given that we do not want to replace ``localhost`` from the examples. Needs further investigation.

**Comment by jspaaks** [comment]
done 352c2634e396d598bc83a5de7672877589b36b3c
