### ISSUE TITLE
Example UploadFileLocalToSftpAbsolutePaths

### ISSUE THREAD

**Issue by sverhoeven** [xenon-middleware/xenon-tutorial#84]

**Comment by jspaaks** [comment]
done.
- bash https://github.com/xenon-middleware/xenon-tutorial/blob/869b0184e79d65cfebf2f58ee213577f75a18061/readthedocs/code-tabs/bash/ 
- java https://github.com/xenon-middleware/xenon-tutorial/blob/869b0184e79d65cfebf2f58ee213577f75a18061/readthedocs/code-tabs/java/src/main/java/nl/esciencecenter/xenon/tutorial/
