### ISSUE TITLE
Example AllTogetherNowWrong 

### ISSUE THREAD

**Issue by sverhoeven** [xenon-middleware/xenon-tutorial#87]
This example does not wait for job completion and thus fails. 
This is confusing to have this as an example so either remove or add error handling.

**Comment by jspaaks** [comment]
Not confusing if the tutorial text is the main entrypoint (which it is now)

For reference
- bash https://github.com/xenon-middleware/xenon-tutorial/blob/869b0184e79d65cfebf2f58ee213577f75a18061/readthedocs/code-tabs/bash/ 
- java https://github.com/xenon-middleware/xenon-tutorial/blob/869b0184e79d65cfebf2f58ee213577f75a18061/readthedocs/code-tabs/java/src/main/java/nl/esciencecenter/xenon/tutorial/
