### ISSUE TITLE
Rename repo to xenon-examples

### ISSUE THREAD

**Issue by sverhoeven** [xenon-middleware/xenon-tutorial#91]
Most other repos in https://github.com/xenon-middleware are named `xenon-*`. The examples  repo should follow this naming scheme.

The repo is linked to in several places, these also need to be updated.

**Comment by jspaaks** [comment]
Agree

**Comment by jspaaks** [comment]
did the simple thing. now let's see what breaks (although github redirects so breakage may not be such a big problem)

**Comment by jspaaks** [comment]
renamed to xenon-tutorial actually
